name: flutterlaravel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  quickalert: ^1.0.1
  dio: ^5.2.1+1
  toast: ^0.3.0
  flutter_secure_storage: ^8.0.0
  device_info_plus: ^9.0.2
  shared_preferences: ^2.1.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  